language: node_js
cache:
  directories:
    - ~/.npm
dist: trusty
sudo: required
notifications:
  email: false
node_js: 10
jobs:
  include:
    - stage: test
      script: npm run test:unit
    - stage: build
      script: npm run dist
    - stage: deploy
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
