name: Node CI

on:
  push:
    branches:
      - master
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and test
        uses: uxland/actions/ci/npm@master
      - name: build
        run: npm run dist
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to npm
        run: npx semantic-release --no-ci --dry-run --debug
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
