name: Node CI

on:
  push:
    branches:
      - master
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      env: 
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - name: npm install and test
        run: |
          npm install
          npm run test:unit
      - name: build
        run: npm run dist
      - name: deploy
        run: npx semantic-release --no-ci --dry-run --debug
