name: Node CI

on:
  push:
    branches:
      - master
      - beta

jobs:
  build:
    name: Build
    description: Install, test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install and test
        uses: uxland/actions/ci/npm@master
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run: npm run dist
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  deploy:
    name: Deploy
    description: Deploys to corresponding registry
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to registry
        run: npx semantic-release --no-ci --dry-run --debug
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
